#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
#ifdef BLOOM_RGBA32F
layout(rgba32f, binding = 0) uniform readonly image2D inputImage;
layout(rgba32f, binding = 1) uniform writeonly image2D outputImage;
#else
layout(rgba16f, binding = 0) uniform readonly image2D inputImage;
layout(rgba16f, binding = 1) uniform writeonly image2D outputImage;
#endif

const float weights[5] = float[](0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(inputImage);
    if (any(greaterThanEqual(pixel, size))) {
        return;
    }

    vec4 result = imageLoad(inputImage, pixel) * weights[0];
    for (int offset = 1; offset < 5; ++offset) {
        result += imageLoad(inputImage, clamp(pixel + ivec2(0, offset), ivec2(0), size - 1)) * weights[offset];
        result += imageLoad(inputImage, clamp(pixel - ivec2(0, offset), ivec2(0), size - 1)) * weights[offset];
    }
    imageStore(outputImage, pixel, result);
}